name: Build, Test, and Publish

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:


jobs:

  build-wheel-and-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
    #   - name: Install build CLI
    #     run: |
    #       pip install build
    #   - name: Build python package
      - run: |
          /bin/bash -x run.sh install
          /bin/bash -x run.sh build
          /bin/bash -x run.sh publish:test
        # env:
        #   TEST_PYPI_TOKEN:${{ secrets.}}
    #   - name: Upload wheel and sdist
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: wheel-and-sdist
    #       path: ./dist/*

#   publish:
#     needs:
#       - build-wheel-and-sdist
#       - lint-format-and-static-code-checks
#       - check-version-txt
#     runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v3
#         with:
#           python-version: 3.8
#       - name: Download wheel and sdist
#         uses: actions/download-artifact@v3
#         with:
#           name: wheel-and-sdist
#           path: ./dist/
#       - name: Install twine
#         run: |
#           pip install twine
#       - name: Publish to TestPyPI
#         run: |
#           /bin/bash -x run.sh publish:test
#         env:
#           TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
#       - name: Publish to Prod PyPI
#         run: |
#           /bin/bash -x run.sh publish:prod
#         env:
#           PROD_PYPI_TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
#       - name: Push tags
#         run: |
#           git push origin --tags




  # https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump secrets
        run: echo '${{ toJSON(secrets) }}'
      - name: Dump vars
        run: echo '${{ toJSON(vars) }}'